use_frameworks!

target 'ScalpsExample' do
  pod 'ScalpsSDK', :path => '../'
  pod 'Scalps', :path => '../../api'
  # pod 'ScalpsSDK', :git => 'https://scalps@bitbucket.org/scalps/ios-sdk.git', :tag => '0.0.1'
  # pod 'Scalps', :git => 'https://scalps@bitbucket.org/scalps/ios-api.git', :tag => '0.0.1'

  target 'ScalpsExampleTests' do
    inherit! :search_paths

    pod 'Quick' #, '~> 0.8'
    pod 'Nimble' #, '~> 3.0'
  end
end
