//
// Match.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** An object representing a match between a subscription and a publication. */
open class Match: JSONEncodable {
    /** The id (UUID) of the match. */
    public var id: String?
    /** The timestamp of the match in seconds since Jan 01 1970 (UTC). */
    public var createdAt: Int64?
    public var publication: Publication?
    public var subscription: Subscription?

    public init() {}

    // MARK: JSONEncodable

    open func encodeToJSON() -> Any {
        var nillableDictionary = [String: Any?]()
        nillableDictionary["id"] = id
        nillableDictionary["createdAt"] = createdAt?.encodeToJSON()
        nillableDictionary["publication"] = publication?.encodeToJSON()
        nillableDictionary["subscription"] = subscription?.encodeToJSON()

        let dictionary: [String: Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
